CREATE OR REPLACE PROCEDURE "USP_DEVELOPMENT_SEASON_MAP"()
RETURNS VARCHAR(256)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
    DECLARE
    DbName VARCHAR(10);
    TableName VARCHAR(256);

    BEGIN

    SELECT XFRM.SVF_GET_SOURCE_DATABASE(''INBOUND'') INTO DbName;

    TableName := CONCAT(DbName, ''.SOURCING.T_DEVELOPMENT_SEASON'');

    
    INSERT OVERWRITE INTO XFRM.DEVELOPMENT_SEASON_MAP
    SELECT MATERIAL_ROLLOUT_CODE, 
       CASE WHEN DEVELOPMENT_SEASON = ''SPRING'' THEN ''Spring''
       WHEN DEVELOPMENT_SEASON = ''SUMMER'' THEN ''Summer''
       WHEN DEVELOPMENT_SEASON = ''FALL'' THEN ''Fall''
       WHEN DEVELOPMENT_SEASON = ''HOLIDAY'' THEN ''Holiday''
       else DEVELOPMENT_SEASON
       END As DEVELOPMENT_SEASON,
      _MODIFIED  
    FROM IDENTIFIER(:TableName)
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY
            MATERIAL_ROLLOUT_CODE
        ORDER BY
            _MODIFIED DESC
    ) = 1;
    ;

    RETURN ''USP_DEVELOPMENT_SEASON_MAP created successfully'';

    END
';