create or replace TABLE DIM_WAVEPOOL_RESEARCH (
	"Created Timestamp" DATE,
	SKU VARCHAR(50),
	"Order Type" VARCHAR(50),
	"Brand" VARCHAR(50),
	"Instore Date" DATE,
	"Flow vs RO" VARCHAR(4),
	"Channel" VARCHAR(11),
	"Demand Qty" NUMBER(28,4),
	"Original Demand Qty" NUMBER(28,4),
	"Carton Rounding Available" VARCHAR(3),
	"Item Description" VARCHAR(750),
	"Available Qty" NUMBER(29,4),
	"Wave Qty" NUMBER(29,4),
	"Wrong Brand" NUMBER(38,4),
	"Wrong Location - Gilbert" NUMBER(29,4),
	"Wrong Location - AVL" NUMBER(29,4),
	"Lost in Warehouse" NUMBER(29,4),
	"Ticketing" NUMBER(29,4),
	"GOH Flag" NUMBER(38,0),
	"Fragile Flag" NUMBER(38,0),
	"Sortable Flag" NUMBER(38,0),
	"Conveyable Flag" NUMBER(38,0),
	"Gilbert Qty" NUMBER(29,4),
	"Gilbert East Qty" NUMBER(29,4),
	"Gilbert West Qty" NUMBER(29,4),
	"Wave Type List" VARCHAR(16777216),
	"AVL FLAG" NUMBER(1,0)
);